name: Manual Update Check

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Update Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x update-template.sh
          ./update-template.sh

      - name: Commit and Push
        if: env.NEW_VERSION != ''
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update helium-browser-bin to version ${{ env.NEW_VERSION }}"
          add: 'srcpkgs/helium-browser-bin/template'
