name: Check Update

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Update Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash update-template.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update helium-browser-bin to version'
          add: 'srcpkgs/helium-browser-bin/template'
